"""Mantém os 200 originais e adiciona 800 produtos com nomes únicos."""
from __future__ import annotations

import csv
import json
import re
from pathlib import Path
from urllib.parse import quote_plus

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data" / "products.json"
USD = 5.18

ORIGINAL = {
    "Tech": range(1, 21),
    "Casa": range(21, 41),
    "Pet": range(41, 61),
    "Moda": range(61, 81),
    "Carro": range(81, 101),
    "Beleza": range(101, 121),
    "Esporte": range(121, 141),
    "Bebê": range(141, 161),
    "Escritório": range(161, 181),
    "Cozinha": range(181, 201),
}

PREFIX = {
    "Tech": "tech",
    "Casa": "casa",
    "Pet": "pet",
    "Moda": "moda",
    "Carro": "carro",
    "Beleza": "beleza",
    "Esporte": "esporte",
    "Bebê": "bebe",
    "Escritório": "escritorio",
    "Cozinha": "cozinha",
}

NEXT_ID = {
    "Tech": 21,
    "Casa": 41,
    "Pet": 61,
    "Moda": 81,
    "Carro": 101,
    "Beleza": 121,
    "Esporte": 141,
    "Bebê": 161,
    "Escritório": 181,
    "Cozinha": 201,
}

# 80 itens novos por categoria: (nome, busca AliExpress, custo USD)
EXTRA = {
    "Tech": [
        ("Suporte Notebook Ventilado", "laptop cooling pad stand", 9.4),
        ("Caixa de Som Bluetooth Mini", "mini bluetooth speaker", 6.8),
        ("Tripé Celular Flexível", "flexible phone tripod", 4.2),
        ("Leitor de Cartão USB-C", "usb c sd card reader", 3.6),
        ("SSD Externo 512GB", "external ssd 512gb", 38.0),
        ("Pen Drive 128GB Metal", "metal usb flash 128gb", 7.1),
        ("Microfone Lapela Sem Fio", "wireless lavalier microphone", 12.4),
        ("Estabilizador Gimbal Celular", "smartphone gimbal stabilizer", 29.5),
        ("Capa AirPods Silicone", "airpods silicone case", 2.3),
        ("Película Câmera iPhone", "iphone camera lens protector", 1.9),
        ("Dock Carregador 4 Portas", "4 port usb charging station", 11.2),
        ("Cabo Lightning 2m", "lightning cable 2m nylon", 2.8),
        ("Carregador Veicular USB Duplo", "dual usb car charger", 3.4),
        ("Antena Wi-Fi USB", "usb wifi adapter 1200mbps", 8.6),
        ("Switch HDMI 3 em 1", "hdmi switch 3 in 1", 7.5),
        ("Controle Bluetooth Game", "bluetooth game controller", 13.8),
        ("VR Box Celular", "vr glasses smartphone", 9.9),
        ("Cooler Celular Gamer", "phone semiconductor cooler", 10.6),
        ("Suporte Monitor Gás", "gas spring monitor arm", 24.0),
        ("Teclado Mecânico 60%", "mechanical keyboard 60 percent", 22.5),
        ("Mouse Gamer RGB", "rgb gaming mouse wired", 8.2),
        ("Headset 7.1 USB", "usb 7.1 gaming headset", 16.4),
        ("Mouse Pad RGB", "rgb mouse pad large", 9.1),
        ("Webcam 4K", "4k webcam autofocus", 28.0),
        ("Microfone Condensador USB", "usb condenser microphone", 18.6),
        ("Braço Articulado Microfone", "microphone boom arm", 11.8),
        ("Filtro Pop Microfone", "mic pop filter", 3.2),
        ("Hub USB 3.0 7 Portas", "usb 3.0 hub 7 port", 10.4),
        ("Repetidor Wi-Fi Mesh", "wifi extender mesh", 14.7),
        ("Roteador Dual Band", "dual band wifi router", 19.2),
        ("Cabo Ethernet 10m", "cat6 ethernet cable 10m", 5.5),
        ("Organizador Cabos Mesa", "desk cable tray organizer", 6.3),
        ("Base Notebook Dobrável", "foldable laptop stand portable", 8.8),
        ("Capa MacBook 13", "macbook 13 inch case", 6.9),
        ("Película MacBook Teclado", "macbook keyboard cover", 3.1),
        ("Leitor Biométrico USB", "usb fingerprint reader", 12.9),
        ("Token USB Segurança", "usb security key", 15.4),
        ("HD Case 2.5", "2.5 hdd enclosure usb c", 7.8),
        ("Dock NVMe M.2", "m.2 nvme enclosure", 13.2),
        ("Ventoinha USB Portátil", "portable usb fan", 4.6),
        ("Luminária Monitor Barra", "monitor light bar", 17.5),
        ("Filtro Privacidade Notebook", "laptop privacy screen 14", 9.7),
        ("Suporte Tablet Mesa", "tablet stand desk aluminum", 6.4),
        ("Caneta Stylus Universal", "universal stylus pen", 5.2),
        ("Teclado Numérico Bluetooth", "bluetooth numeric keypad", 8.1),
        ("Apresentador Laser USB", "usb laser presenter", 6.7),
        ("Gravador de Voz Digital", "digital voice recorder", 14.3),
        ("Rádio Relógio Bluetooth", "bluetooth alarm clock radio", 11.6),
        ("Tradutor Eletrônico Bolso", "pocket language translator", 32.0),
        ("GPS Portátil Moto", "motorcycle gps navigator", 41.0),
        ("Câmera Esportiva 4K", "action camera 4k waterproof", 26.8),
        ("Bastão Selfie Tripé", "selfie stick tripod bluetooth", 5.9),
        ("Luz LED Vídeo RGB", "rgb video light panel", 12.2),
        ("Softbox Mesa Foto", "tabletop photo softbox", 16.9),
        ("Fundo Infinito Foto", "photo backdrop kit", 13.5),
        ("Anel LED 12 Polegadas", "12 inch ring light tripod", 14.8),
        ("Suporte Celular Pescoço", "neck phone holder lazy", 4.4),
        ("Pulseira Antiestática", "anti static wrist strap", 2.1),
        ("Kit Limpeza Tela 5pç", "screen cleaning kit 5pcs", 3.8),
        ("Soprador Pó Elétrico", "electric air duster", 18.2),
        ("Termômetro PC Digital", "pc digital thermometer", 5.6),
        ("Controlador RGB Fan Hub", "rgb fan hub controller", 9.3),
        ("Pasta Térmica 4g", "thermal paste 4g", 3.4),
        ("Pad Térmico SSD", "ssd thermal pad", 2.7),
        ("Cabo DisplayPort 2m", "displayport cable 2m 8k", 6.8),
        ("Conversor VGA HDMI", "vga to hdmi converter", 5.1),
        ("Split HDMI 1x2", "hdmi splitter 1x2", 7.4),
        ("Extensor HDMI 30m", "hdmi extender 30m", 15.8),
        ("Capturadora HDMI USB", "hdmi video capture card", 11.9),
        ("Placa Som USB Externa", "usb external sound card", 6.2),
        ("DAC Amplificador Fone", "usb dac headphone amp", 19.6),
        ("Fone Oversized Studio", "studio monitor headphones", 21.4),
        ("Amp Fone Portátil", "portable headphone amplifier", 14.1),
        ("Case HD 3.5", "3.5 hdd docking station", 16.3),
        ("Gabinete Mini ITX", "mini itx case", 34.0),
        ("Fonte 650W 80 Plus", "650w 80 plus psu", 42.0),
        ("Cooler CPU Torre", "cpu air cooler tower", 23.5),
        ("Watercooler 240mm", "240mm aio liquid cooler", 48.0),
        ("Memória RAM 16GB DDR4", "ddr4 16gb ram 3200", 29.0),
        ("SSD 1TB NVMe", "1tb nvme ssd", 52.0),
    ],
    "Casa": [
        ("Capa Colchão Impermeável", "waterproof mattress protector", 8.4),
        ("Protetor Travesseiro Kit 2", "pillow protector 2 pack", 5.2),
        ("Edredom Casal Microfibra", "microfiber comforter queen", 18.6),
        ("Jogo de Cama 4 Peças", "bedding set 4pcs", 16.2),
        ("Cortina Voil Sala", "sheer curtains living room", 11.4),
        ("Varão Cortina 2m", "curtain rod 2m", 7.8),
        ("Tapete Sala 160x230", "living room rug 160x230", 22.0),
        ("Passadeira Cozinha Antiderrapante", "kitchen runner non slip", 9.6),
        ("Capacho Entrada Borracha", "rubber door mat", 6.3),
        ("Espelho Aditivo Corredor", "full length wall mirror", 19.4),
        ("Prateleira Flutuante Kit 3", "floating shelves 3 pack", 10.8),
        ("Nicho Parede Madeira", "wood wall niche shelf", 8.9),
        ("Cabideiro Chão Industrial", "industrial floor coat rack", 17.5),
        ("Gancho Adesivo Forte Kit 10", "heavy duty adhesive hooks 10", 3.7),
        ("Organizadora Closet Tecido", "fabric closet organizer", 9.2),
        ("Saco a Vácuo Kit 8", "vacuum storage bags 8", 7.4),
        ("Cesto Roupa Suja Dobrável", "foldable laundry hamper", 8.1),
        ("Tábua Passar Roupa Mesa", "tabletop ironing board", 12.6),
        ("Ferro Vapor Compacto", "travel steam iron", 14.8),
        ("Vaporizador Roupas Vertical", "garment steamer vertical", 21.0),
        ("Aspirador Robô Mini", "mini robot vacuum", 46.0),
        ("Aspirador Vertical Sem Fio", "cordless stick vacuum", 39.0),
        ("Rodo Mágico 3 em 1", "magic squeeze mop", 8.7),
        ("Balde Esfregão Giratório", "spin mop bucket set", 13.9),
        ("Escova Vaso Sanitário Fechada", "closed toilet brush holder", 5.8),
        ("Dispenser Papel Higiênico", "toilet paper holder wall", 4.6),
        ("Porta Escova Dente Parede", "wall toothbrush holder", 3.9),
        ("Prateleira Box Cantoneira", "shower corner caddy", 7.2),
        ("Cortina Box Impermeável", "waterproof shower curtain", 6.8),
        ("Tapete Banheiro Antiderrapante", "bathroom non slip mat", 5.4),
        ("Assento Vaso Soft Close", "soft close toilet seat", 16.5),
        ("Ducha Higiénica Inox", "bidet sprayer stainless", 11.3),
        ("Filtro Torneira Cozinha", "faucet water filter", 9.8),
        ("Arejador Torneira 360", "360 faucet aerator", 3.5),
        ("Suporte Papel Toalha", "paper towel holder", 4.8),
        ("Lixeira Banheiro Com Tampa", "bathroom trash can lid", 7.6),
        ("Saboneteira Automática", "automatic soap dispenser", 10.2),
        ("Toalheiro Aquecido Elétrico", "electric heated towel rack", 28.4),
        ("Cabide Veludo Kit 20", "velvet hangers 20 pack", 8.3),
        ("Organizadora Gaveta Sutiã", "bra drawer organizer", 6.1),
        ("Caixa Sapato Transparente Kit 6", "clear shoe boxes 6", 12.4),
        ("Sapateira Porta Tecido", "over door shoe organizer", 9.5),
        ("Banco Sapateira Entrada", "entryway shoe bench", 24.0),
        ("Porta-Chaves Parede", "wall key holder", 4.2),
        ("Quadro Porta-Retrato Kit 5", "photo frame set 5", 8.8),
        ("Vaso Cerâmica Decorativo", "ceramic decorative vase", 7.9),
        ("Planta Artificial 80cm", "artificial plant 80cm", 9.4),
        ("Guirlanda Porta", "front door wreath", 6.7),
        ("Difusor Aroma Elétrico", "electric aroma diffuser", 11.6),
        ("Vela Aromática Kit 3", "scented candles 3 pack", 7.1),
        ("Incensário e Incenso", "incense holder set", 4.4),
        ("Umidificador Torre 4L", "tower humidifier 4l", 26.0),
        ("Desumidificador Armário Kit 6", "closet dehumidifier packs 6", 5.3),
        ("Purificador Ar Portátil", "portable air purifier", 32.0),
        ("Ventilador de Mesa USB", "usb desk fan quiet", 8.6),
        ("Aquecedor Portátil 1500W", "1500w space heater", 29.5),
        ("Luminária Chão Tripé", "tripod floor lamp", 22.8),
        ("Abajur Cúpula Tecido", "fabric shade table lamp", 14.2),
        ("Fita LED Branco Quente 5m", "warm white led strip 5m", 6.9),
        ("Sensor Presença Lâmpada", "motion sensor light bulb", 5.7),
        ("Lâmpada Inteligente RGB", "smart rgb light bulb", 6.4),
        ("Interruptor Inteligente Wi-Fi", "wifi smart switch", 8.2),
        ("Tomada Inteligente Kit 4", "smart plug 4 pack", 14.6),
        ("Campainha Sem Fio", "wireless doorbell", 9.1),
        ("Fechadura Digital Senha", "digital password door lock", 38.0),
        ("Olho Mágico Digital", "digital door viewer", 21.5),
        ("Trava Porta Reforçada", "door security bar", 7.3),
        ("Rede Proteção Janela", "window safety net", 11.8),
        ("Película Vidro Jateado", "frosted window film", 6.6),
        ("Mosquiteiro Janela Ímã", "magnetic window screen", 8.4),
        ("Calha Pingadeira Janela", "window rain drip guard", 5.9),
        ("Protetor Porta Calha", "door draft stopper", 4.7),
        ("Isolante Térmico Janela", "window insulation film", 7.8),
        ("Cortina Blackout Imã", "magnetic blackout curtains", 15.4),
        ("Persiana Rolô 80cm", "roller blinds 80cm", 13.2),
        ("Varal Chão Dobrável", "folding clothes drying rack", 12.9),
        ("Prendedor Roupa Inox Kit 30", "stainless clothespins 30", 3.6),
        ("Cesto Prendedor com Ímã", "magnetic clothespin bag", 3.2),
        ("Cabide Saia Clip Kit 10", "skirt clip hangers 10", 6.5),
        ("Tábua Passar com Cavalete", "ironing board with stand", 19.8),
    ],
    "Pet": [
        ("Coleira Antipulgas Ajustável", "flea tick dog collar adjustable", 4.8),
        ("Coleira Couro Personalizada", "personalized leather dog collar", 6.2),
        ("Guia Mãos Livres Corrida", "hands free running dog leash", 8.4),
        ("Peitoral Gato Escape-Proof", "escape proof cat harness", 7.1),
        ("Focinheira Ajustável", "adjustable dog muzzle", 5.3),
        ("Bebedouro Fonte 2L", "2l pet water fountain", 16.8),
        ("Comedouro Automático Timer", "automatic pet feeder timer", 24.5),
        ("Comedouro Inox Antiderrapante", "stainless non slip dog bowl", 6.4),
        ("Jogo Americano Pet Silicone", "silicone pet feeding mat", 4.6),
        ("Cama Donut Cão", "donut calming dog bed", 18.2),
        ("Manta Pet Pelúcia", "plush pet blanket", 7.9),
        ("Casinha Plástico Cão Médio", "plastic dog house medium", 32.0),
        ("Tenda Cama Gato", "cat tent bed", 11.4),
        ("Arranhador Cartão Ondulado", "cardboard cat scratcher", 5.8),
        ("Árvore Gato 120cm", "cat tree 120cm", 38.0),
        ("Prateleira Parede Gato Kit 3", "cat wall shelves 3", 16.6),
        ("Brinquedo Interativo Pet", "interactive dog puzzle toy", 8.7),
        ("Bolinha LED Gato", "led ball cat toy", 3.9),
        ("Varinha Pena Gato", "cat feather wand", 3.2),
        ("Corda Algodão Cão", "cotton rope dog toy", 4.1),
        ("Frisbee Borracha Pet", "rubber dog frisbee", 4.4),
        ("Osso Nylon Sabor Bacon", "bacon nylon dog chew", 3.8),
        ("Snack Mat Lambe Lambe", "lick mat dog", 5.2),
        ("Escova Dente Dedo Pet Kit 3", "finger toothbrush dog 3", 2.6),
        ("Creme Dental Pet", "dog toothpaste", 4.3),
        ("Cortador Unha Pet com LED", "pet nail clipper led", 6.9),
        ("Secador Pet 2 em 1", "pet dryer brush 2 in 1", 19.4),
        ("Toalha Banho Superabsorvente", "microfiber pet towel", 6.1),
        ("Shampoo Neutro Cão 500ml", "dog shampoo 500ml", 5.7),
        ("Lenço Umedecido Pet Kit 80", "pet wipes 80", 4.2),
        ("Tapete Higiênico 50un", "puppy pads 50 count", 11.8),
        ("Caixa Areia Gato Fechada", "covered cat litter box", 17.5),
        ("Pá Areia Gato", "cat litter scoop", 2.8),
        ("Areia Sílica 4L", "silica cat litter 4l", 9.6),
        ("Filtro Fonte Pet Kit 4", "pet fountain filters 4", 6.5),
        ("Porta Petisco Clicker", "dog treat pouch clicker", 5.4),
        ("Clicker Adestramento", "dog training clicker", 2.2),
        ("Apito Ultrassônico", "ultrasonic dog whistle", 3.1),
        ("Cercadinho Pet Dobrável", "foldable pet playpen", 22.8),
        ("Grade Porta Pet", "pet gate doorway", 19.6),
        ("Rampa Sofá Pet", "dog sofa ramp", 18.4),
        ("Degrau Pet 2 Degraus", "2 step pet stairs", 15.2),
        ("Cinto Segurança Carro Pet", "dog car seat belt", 4.9),
        ("Capa Banco Carro Pet", "car back seat pet cover", 13.7),
        ("Bolsa Transporte Gato Rígida", "hard cat carrier", 21.0),
        ("Mochila Cápsula Pet", "bubble backpack pet carrier", 16.9),
        ("Carrinho Passeio Pet", "pet stroller", 34.0),
        ("Capa Chuva Cão", "dog raincoat", 7.4),
        ("Botinha Pet Kit 4", "dog boots 4pcs", 6.8),
        ("Suéter Pet Tricot", "knit dog sweater", 7.2),
        ("Bandana Pet Kit 3", "dog bandana 3 pack", 3.6),
        ("Laço Cabelo Pet", "pet hair bows", 2.4),
        ("Coleira Gravata", "dog bow tie collar", 3.8),
        ("Identificação Tag Gravada", "engraved pet id tag", 2.9),
        ("GPS Coleira Bluetooth", "bluetooth pet tracker collar", 14.8),
        ("Câmera Pet Wi-Fi", "pet camera treat toss", 36.0),
        ("Bebedouro Garrafa Viagem", "travel pet water bottle", 5.1),
        ("Pote Dobrável Viagem", "collapsible dog bowl", 3.4),
        ("Manta Assento Carro", "car seat pet hammock", 12.2),
        ("Rede Porta Pet", "car pet barrier net", 8.6),
        ("Escova Vapor Pet", "steam pet brush", 11.3),
        ("Aspirador Pelos Sofá", "pet hair vacuum sofa", 15.8),
        ("Rolo Tira Pelos Kit 2", "lint roller pet 2", 3.3),
        ("Capa Sofá Pet Impermeável", "waterproof sofa cover pets", 14.6),
        ("Protetor Canto Móvel Pet", "furniture corner guards pets", 4.1),
        ("Repelente Spray Pet", "pet safe insect spray", 5.6),
        ("Coleira Refletiva Noturna", "reflective dog collar night", 3.9),
        ("Pingente LED Coleira", "led pet collar pendant", 3.2),
        ("Cama Aquecida Elétrica", "heated pet bed", 23.4),
        ("Almofada Gel Resfriamento", "cooling pet mat gel", 10.8),
        ("Fonte Externa Gato", "outdoor cat waterer", 9.2),
        ("Comedouro Pássaro Janela", "window bird feeder", 8.4),
        ("Brinquedo Hamster Roda", "hamster exercise wheel", 6.7),
        ("Gaiola Hamster Completa", "hamster cage set", 21.5),
        ("Aquário Kit 10L", "10l aquarium starter kit", 19.8),
        ("Filtro Aquário Interno", "internal aquarium filter", 8.9),
        ("Termostato Aquário", "aquarium heater thermostat", 9.4),
        ("Rede Peixe Aquário", "aquarium fish net", 2.3),
        ("Casinha Coelho Madeira", "wooden rabbit house", 26.0),
        ("Feno Rack Coelho", "rabbit hay feeder", 6.1),
    ],
    "Moda": [
        ("Bolsa Tiracolo Couro", "leather messenger bag women", 12.4),
        ("Mochila Couro Mini", "mini leather backpack", 14.8),
        ("Clutch Festa Brilho", "sparkle evening clutch", 8.6),
        ("Carteira Feminina Grande", "large women wallet", 7.2),
        ("Porta-Passaporte Couro", "leather passport holder", 5.4),
        ("Cinto Feminino Fivela Dourada", "women gold buckle belt", 6.1),
        ("Cinto Elástico Sem Fivela", "buckleless stretch belt", 4.8),
        ("Óculos Retrô Acetato", "retro acetate sunglasses", 7.9),
        ("Óculos Clip-On Ímã", "magnetic clip on glasses", 8.4),
        ("Cordão Óculos Elos", "glasses chain strap", 3.6),
        ("Boné Trucker Telinha", "trucker mesh cap", 4.2),
        ("Gorro Lã Unissex", "unisex wool beanie", 5.1),
        ("Faixa Cabelo Cetim", "satin headband", 3.3),
        ("Scrunchie Cetim Kit 6", "satin scrunchies 6", 3.8),
        ("Presilha Jacaré Kit 10", "hair claw clips 10", 4.1),
        ("Tiara Acolchoada", "padded headband women", 3.9),
        ("Brinco Pérola Gota", "pearl drop earrings", 4.6),
        ("Brinco Ear Cuff Kit 3", "ear cuff set 3", 3.4),
        ("Colar Choker Veludo", "velvet choker necklace", 3.2),
        ("Colar Camadas 3 Fios", "layered necklace 3", 5.8),
        ("Pulseira Riviera", "tennis bracelet", 6.9),
        ("Anel Ajustável Prata", "adjustable silver ring", 3.7),
        ("Tornozeleira Delicada", "dainty anklet", 3.1),
        ("Piercing Falso Kit 4", "fake piercing set 4", 2.8),
        ("Relógio Digital Quadrado", "square digital watch", 9.4),
        ("Relógio Feminino Rose", "rose gold women watch", 11.6),
        ("Pulseira Relógio Couro Extra", "watch leather strap", 4.4),
        ("Meia Cano Alto Kit 5", "crew socks 5 pairs", 5.6),
        ("Meia Térmica Inverno", "thermal winter socks", 4.9),
        ("Meia Soquete Colorida Kit 8", "ankle socks 8 pairs", 5.2),
        ("Cinta Modeladora", "waist trainer shaper", 9.8),
        ("Sutiã Sem Alça", "strapless bra", 7.4),
        ("Sutiã Adesivo", "adhesive bra", 6.2),
        ("Calcinha Sem Costura Kit 5", "seamless panties 5", 8.1),
        ("Cueca Boxer Kit 4", "boxer briefs 4 pack", 9.6),
        ("Camiseta Térmica Unissex", "thermal undershirt unisex", 8.8),
        ("Segunda Pele Calça", "thermal base layer pants", 9.2),
        ("Pijama Cetim 2 Peças", "satin pajama set", 14.5),
        ("Robe Cetim", "satin robe women", 11.8),
        ("Chinelo Nuvem", "cloud slide slippers", 7.6),
        ("Pantufa Pelúcia", "plush indoor slippers", 6.8),
        ("Sandália Rasteira Tiras", "strappy flat sandals", 8.4),
        ("Cinto Tirante Calça", "no buckle belt jeans", 4.3),
        ("Suspensório Unissex", "unisex suspenders", 5.7),
        ("Gravata Slim", "slim necktie", 5.4),
        ("Lenço Pescoço Homem", "men silk neckerchief", 6.3),
        ("Carteira Clip Dinheiro", "money clip wallet", 5.9),
        ("Chaveiro Couro", "leather keychain", 2.9),
        ("Porta-Moedas Zíper", "zipper coin purse", 3.5),
        ("Nécessaire Transparente Avião", "clear toiletry bag tsa", 5.8),
        ("Organizadora Mala 7pç", "packing cubes 7pcs", 11.2),
        ("Capa Mala Elástica", "elastic luggage cover", 7.1),
        ("Cadeado TSA Mala", "tsa luggage lock", 4.6),
        ("Etiqueta Mala Couro", "leather luggage tag", 3.4),
        ("Pochete Couro Cintura", "leather waist bag", 9.3),
        ("Shoulder Bag Nylon", "nylon shoulder bag", 8.7),
        ("Tote Lona Grande", "canvas tote bag large", 7.8),
        ("Bolsa Térmica Almoço", "insulated lunch tote", 8.2),
        ("Guarda-Chuva Automático", "automatic compact umbrella", 7.4),
        ("Poncho Chuva Transparente", "clear rain poncho", 3.8),
        ("Capa Chuva Bike", "bike rain poncho", 6.6),
        ("Luvas Direção Couro", "leather driving gloves", 8.9),
        ("Luva Sem Dedo Tricot", "fingerless knit gloves", 4.7),
        ("Echarpe Xadrez", "plaid scarf unisex", 7.2),
        ("Gola Gola Alta Tricot", "knit neck warmer", 5.3),
        ("Boina Francesa", "french beret wool", 6.8),
        ("Chapéu Panama Palha", "panama straw hat", 9.6),
        ("Viseira Esportiva", "sun visor cap", 4.1),
        ("Cinto Faixa Cetim", "satin sash belt", 3.6),
        ("Broche Flor", "flower brooch pin", 3.2),
        ("Lenço Bolso Terno", "pocket square", 3.9),
        ("Abotoadura Metal", "metal cufflinks", 5.5),
        ("Alfinete Gravata", "tie pin clip", 3.1),
        ("Pulseira Couro Homem", "men leather bracelet", 4.8),
        ("Colar Cruz Aço", "stainless cross necklace", 4.2),
        ("Anel Selo Homem", "men signet ring", 5.1),
        ("Óculos Leitura +2.0", "reading glasses +2.0", 4.4),
        ("Cordão Máscara/Óculos", "mask glasses strap", 2.6),
        ("Porta-Lenço Bolso", "pocket tissue holder", 2.8),
        ("Espelho Bolsa LED", "led compact mirror purse", 5.2),
    ],
    "Carro": [
        ("Suporte Celular Painel", "dashboard phone mount", 4.6),
        ("Carregador Indução Carro", "car wireless charger mount", 12.8),
        ("Transmissor FM Bluetooth", "bluetooth fm transmitter", 8.4),
        ("Caixa Som Bluetooth Carro", "car bluetooth speaker", 11.2),
        ("Câmera Frontal ADAS", "adas dash camera", 22.6),
        ("Sensor Estacionamento Kit 4", "parking sensors 4pcs", 14.8),
        ("Central Multimídia 7 Pol", "7 inch car android stereo", 58.0),
        ("Espelho Retrovisor Wide", "wide angle rear view mirror", 7.4),
        ("Calha Chuva Universal", "universal rain guards", 9.6),
        ("Friso Para-Choque", "car bumper protector strip", 5.2),
        ("Protetor Maçaneta Kit 4", "door handle scratches 4", 3.4),
        ("Soleira Porta Adesivo", "door sill protector", 4.8),
        ("Capa Banco Couro Universal", "universal leather seat cover", 21.5),
        ("Almofada Encosto Carro", "car seat lumbar cushion", 8.7),
        ("Travesseiro Pescoço Carro", "car neck pillow memory", 6.9),
        ("Manta Viagem Carro", "car travel blanket", 7.8),
        ("Organizador Porta-Malas", "trunk organizer collapsible", 11.4),
        ("Rede Porta-Malas", "car trunk cargo net", 6.2),
        ("Gancho Porta-Malas", "trunk grocery hook", 3.6),
        ("Tapete Porta-Malas", "car trunk liner", 13.2),
        ("Protetor Assento Infantil", "child car seat protector", 9.1),
        ("Espelho Bebê Banco Traseiro", "baby car mirror back seat", 7.3),
        ("Protetor Sol Lateral", "car side window sun shade", 5.8),
        ("Cortina Ímã Carro Kit 2", "magnetic car curtains 2", 8.2),
        ("Aromatizador Ventilação", "vent clip air freshener", 2.9),
        ("Purificador Ozônio Carro", "car ozone ionizer", 10.6),
        ("Umidificador Carro USB", "car usb humidifier", 6.4),
        ("Aspirador Sem Fio Carro", "cordless car vacuum", 18.8),
        ("Escova Detalhamento Kit 9", "car detailing brush 9", 7.6),
        ("Toalha Microfibra Auto Kit 5", "car microfiber towels 5", 6.8),
        ("Cera Líquida 500ml", "car liquid wax 500ml", 8.4),
        ("Revitalizador Plásticos", "plastic restorer car", 6.1),
        ("Limpa Farol Kit", "headlight restoration kit", 9.3),
        ("Película Farol Fumê", "smoke headlight tint", 5.4),
        ("Lâmpada LED H4 Par", "h4 led headlight pair", 14.2),
        ("Lâmpada LED T10 Kit 10", "t10 led bulbs 10", 4.7),
        ("Fita LED Interior Carro", "car interior led strip", 6.5),
        ("Projetor Logo Porta", "car door logo projector", 8.9),
        ("Antena Shark", "shark fin antenna", 5.6),
        ("Capa Volante Couro Costura", "leather steering cover sew", 7.2),
        ("Manopla Câmbio Universal", "universal gear shift knob", 6.3),
        ("Pedaleira Alumínio Kit", "aluminum car pedals", 9.8),
        ("Capa Freio Mão", "handbrake cover", 3.8),
        ("Organizador Console", "car console organizer", 5.9),
        ("Porta-Copo Carro", "car cup holder expander", 4.2),
        ("Bandeja Volante Notebook", "steering wheel laptop tray", 8.1),
        ("Trava Volante Antifurto", "steering wheel lock", 11.6),
        ("Trava Pedal Antifurto", "car pedal lock", 12.4),
        ("Alarme Presença Bluetooth", "bluetooth car alarm", 16.8),
        ("Localizador GPS Carro", "car gps tracker", 18.4),
        ("Câmera 360 Graus", "360 car camera system", 42.0),
        ("Sensor Pressão Pneu TPMS", "tpms tire monitor", 19.6),
        ("Calibrador Digital Pneu", "digital tire gauge", 5.7),
        ("Chave Cruz Rodas", "lug wrench cross", 8.6),
        ("Macaco Elétrico 12V", "12v electric car jack", 34.0),
        ("Chave Impacto 12V", "12v impact wrench car", 28.5),
        ("Cabo Chupeta 800A", "jumper cables 800a", 13.8),
        ("Auxiliar Partida 1000A", "jump starter 1000a", 36.0),
        ("Compressor Digital Display", "digital tire inflator", 17.2),
        ("Funil Combustível Flexível", "flexible fuel funnel", 3.4),
        ("Galão Combustível 5L", "5l fuel canister", 9.7),
        ("Tapete Porta Copo LED", "led cup holder mat", 4.9),
        ("Protetor Cinto Conforto", "seat belt comfort pad", 3.2),
        ("Clipe Cinto Segurança", "seat belt clip adjuster", 2.6),
        ("Extintor Automotivo", "car fire extinguisher", 12.8),
        ("Colete Refletivo Kit", "reflective safety vest car", 4.4),
        ("Triângulo Sinalização LED", "led warning triangle", 8.3),
        ("Martelo Emergência Quebra-Vidro", "car emergency hammer", 5.1),
        ("Kit Reparo Pneu", "tire repair kit", 7.9),
        ("Capa Carro Forro Total", "full car cover outdoor", 18.6),
        ("Capa Retrovisor Chuva Kit 2", "mirror rain visor 2", 4.8),
        ("Defletor Capô", "car hood deflector", 11.4),
        ("Spoiler Universal", "universal car spoiler", 16.2),
        ("Grade Colmeia Universal", "universal honeycomb grille", 13.5),
        ("Emblema Metal 3D", "3d metal car emblem", 3.7),
        ("Calota Aro 14 Kit 4", "hubcaps 14 inch 4", 14.8),
        ("Válvula Pneu Colorida Kit", "colored tire valve caps", 2.4),
        ("Corrente Neve Têxtil", "textile snow chains", 19.2),
        ("Raspador Gelo LED", "led ice scraper", 4.6),
        ("Desembaçador Spray", "defogger spray car", 4.1),
    ],
    "Beleza": [
        ("Secador Ions 2000W", "ionic hair dryer 2000w", 18.4),
        ("Prancha Cerâmica 230°", "ceramic hair straightener 230", 15.6),
        ("Babyliss Cacheador 25mm", "25mm curling wand", 13.8),
        ("Difusor Cachos Universal", "universal hair diffuser", 6.2),
        ("Escova Térmica Redonda", "round thermal brush", 5.8),
        ("Pente Garfo Afro", "afro pick comb", 2.4),
        ("Escova Desembaraçante", "detangling hair brush", 4.6),
        ("Touca Cetim Dormir", "satin sleep bonnet", 4.1),
        ("Fronha Cetim Kit 2", "satin pillowcase 2", 7.4),
        ("Spray Protetor Térmico", "heat protectant spray", 5.3),
        ("Óleo Capilar Argan 50ml", "argan hair oil 50ml", 6.8),
        ("Máscara Capilar Potão", "hair mask jar", 7.2),
        ("Elástico Sem Costura Kit 50", "seamless hair ties 50", 3.6),
        ("Presilha Banana", "banana hair clip", 2.8),
        ("Modelador Beach Waves", "beach waves hair waver", 16.4),
        ("Aparador Barba 5 em 1", "5 in 1 beard trimmer", 14.8),
        ("Pente Barba Madeira", "wooden beard comb", 3.2),
        ("Óleo Barba 30ml", "beard oil 30ml", 5.6),
        ("Balm Barba", "beard balm", 5.9),
        ("Toalha Barba Avental", "beard shaving apron", 6.4),
        ("Navalha Navalhete", "straight razor shavette", 7.1),
        ("Espuma Barbear Dispenser", "shaving foam dispenser", 8.3),
        ("Espelho Aumento 10x", "10x magnifying mirror", 6.7),
        ("Espelho Articulado Parede", "wall mounted makeup mirror", 11.8),
        ("Paleta Pincéis 12pç", "makeup brush set 12", 8.6),
        ("Esponja Maquiagem Kit 6", "makeup sponges 6", 4.2),
        ("Necessaire Pincel Cilindro", "brush holder makeup bag", 5.4),
        ("Cílios Postiços Kit 10", "false eyelashes 10 pairs", 5.1),
        ("Cola Cílios Transparente", "clear lash glue", 2.9),
        ("Curvex Metal", "metal eyelash curler", 3.4),
        ("Delineador Carimbo", "winged eyeliner stamp", 4.8),
        ("Lápis Sobrancelha 3 Cores", "3 color eyebrow pencil", 3.7),
        ("Kit Henna Sobrancelha", "eyebrow henna kit", 6.3),
        ("Removedor Maquiagem Elétrico", "electric makeup remover", 9.4),
        ("Discos Algodão Reutilizáveis", "reusable cotton rounds", 4.4),
        ("Faixa Make Velcro", "velcro spa headband", 3.1),
        ("Rolo Gelo Facial", "ice roller face", 6.9),
        ("Máscara LED Facial", "led face mask therapy", 22.5),
        ("Derma Roller 0.25", "derma roller 0.25mm", 5.8),
        ("Extrator Cravos Kit 4", "blackhead remover kit 4", 4.6),
        ("Vaporizador Facial Ozônio", "ozone facial steamer", 18.2),
        ("Escova Limpeza Poros", "pore cleansing brush", 8.1),
        ("Sérum Gotas Conta-Gotas", "dropper serum bottle empty", 2.6),
        ("Espátula Cosmética Kit", "cosmetic spatula set", 3.3),
        ("Balança Cosméticos 0.01g", "jewelry scale 0.01g", 6.4),
        ("Aparador Sobrancelha Elétrico", "electric eyebrow trimmer", 7.6),
        ("Depilador Luz Pulsada Mini", "mini ipl hair removal", 34.0),
        ("Cera Quente Kit", "hot wax kit home", 11.4),
        ("Folhas Cera Fria 40un", "cold wax strips 40", 6.8),
        ("Lixa Unha Elétrica", "electric nail drill", 13.6),
        ("Cabine UV/LED 48W", "48w uv led nail lamp", 16.8),
        ("Kit Unha Gel Iniciante", "gel nail starter kit", 14.2),
        ("Alicate Cutícula Inox", "cuticle nipper stainless", 4.9),
        ("Empurrador Cutícula", "cuticle pusher", 2.4),
        ("Lixa Buffer Kit 20", "nail buffer files 20", 3.8),
        ("Secador Esmalte Spray", "nail polish dryer spray", 4.1),
        ("Removedor Esmalte Pump", "nail polish remover pump", 5.2),
        ("Separador Dedos Silicone", "toe separators silicone", 2.7),
        ("Palmilha Conforto Gel", "gel insole comfort", 5.6),
        ("Almofada Metatarso", "metatarsal pads", 3.9),
        ("Protetor Calcanhar Kit 6", "heel cushions 6", 3.5),
        ("Removedor Calo Elétrico", "electric callus remover", 9.8),
        ("Pedicure Banheira", "foot spa bath", 21.4),
        ("Pedra-Pomes Kit 2", "pumice stone 2", 3.2),
        ("Creme Mãos Dispenser", "hand cream dispenser", 4.6),
        ("Luva Hidratante Noite", "overnight moisturizing gloves", 6.1),
        ("Meia Hidratante Spa", "spa moisturizing socks", 5.4),
        ("Perfume Átomo 5ml Kit 3", "refillable perfume atomizer 3", 6.7),
        ("Organizadora Batom Acrílico", "acrylic lipstick organizer", 7.8),
        ("Espelho Bolso Aumento", "pocket magnifying mirror", 3.4),
        ("Pinça Pontas Kit 3", "tweezers set 3", 4.2),
        ("Afiador Navalha", "razor sharpener", 5.1),
        ("Capa Escova Dente Viagem", "toothbrush travel cover", 2.3),
        ("Irrigador Oral Portátil", "portable water flosser", 17.6),
        ("Clareador Dental LED", "led teeth whitening kit", 12.4),
        ("Fio Dental Automático", "automatic floss dispenser", 5.8),
        ("Limpador Língua Cobre", "copper tongue scraper", 3.6),
        ("Enxaguante Viagem Kit", "travel mouthwash bottles", 3.1),
        ("Necessaire Pendurar Gancho", "hanging toiletry bag hook", 8.4),
        ("Espelho Chuveiro Antinévoa", "anti fog shower mirror", 5.2),
    ],
    "Esporte": [
        ("Kettlebell 8kg", "8kg kettlebell", 16.8),
        ("Kettlebell 12kg", "12kg kettlebell", 21.4),
        ("Anilha Revestida 5kg Par", "5kg weight plates pair", 18.6),
        ("Barra W Musculação", "ez curl bar", 24.0),
        ("Pegador Remada", "cable row handle", 7.2),
        ("Cinto Musculação Couro", "leather weightlifting belt", 13.8),
        ("Munhequeira Academia Kit 2", "wrist wraps gym 2", 5.4),
        ("Strap Levantamento", "lifting straps", 4.8),
        ("Hand Grip Ajustável Par", "adjustable hand gripper pair", 6.6),
        ("Bola Massageadora Espinho", "spiky massage ball", 3.4),
        ("Rolo Massageador Bastão", "muscle massage stick", 7.8),
        ("Gatilho Ponto Massageador", "trigger point massager", 5.9),
        ("Tapete Exercício Dobrável", "folding exercise mat", 14.2),
        ("Bloco Yoga Kit 2", "yoga blocks 2", 6.4),
        ("Cinta Yoga Algodão", "yoga strap cotton", 4.2),
        ("Bolster Yoga", "yoga bolster pillow", 15.6),
        ("Meia Yoga Antiderrapante", "yoga socks non slip", 4.6),
        ("Roda Yoga", "yoga wheel", 12.8),
        ("Anel Pilates", "pilates ring", 8.1),
        ("Slider Disco Kit 2", "core sliders 2", 5.2),
        ("TRX Fita Suspensão", "suspension trainer straps", 17.4),
        ("Barra Porta Flexão", "doorway push up bar", 11.6),
        ("Apoio Flexão Rotativo", "rotating push up stands", 9.3),
        ("Paralelas Mini", "mini parallettes", 14.8),
        ("Abdominal Roda", "ab roller wheel", 6.8),
        ("Banco Abdominal", "ab sit up bench", 32.0),
        ("Corda Naval 9m", "9m battle rope", 26.5),
        ("Cone Agilidade Kit 10", "agility cones 10", 7.4),
        ("Escada Agilidade 6m", "agility ladder 6m", 8.6),
        ("Barreira Agilidade Kit 5", "agility hurdles 5", 11.2),
        ("Corda Pular Contador", "jump rope with counter", 5.7),
        ("Corda Pular Aço", "steel speed jump rope", 6.3),
        ("Luvas Boxe 12oz", "12oz boxing gloves", 16.4),
        ("Bandagem Boxe 3m Par", "boxing hand wraps 3m", 4.4),
        ("Saco Pancada Vazio", "empty punching bag", 19.8),
        ("Suporte Saco Teto", "punching bag ceiling mount", 12.6),
        ("Protetor Bucal Boxe", "boxing mouth guard", 3.8),
        ("Capacete Treino", "training headgear", 15.2),
        ("Caneleira Muay Thai", "muay thai shin guards", 14.6),
        ("Kimono Leve Jiu-Jitsu", "lightweight bjj gi", 42.0),
        ("Faixa Jiu-Jitsu", "bjj belt", 8.4),
        ("Joelheira Vôlei Par", "volleyball knee pads", 7.9),
        ("Cotoveleira Ciclismo", "cycling elbow pads", 6.8),
        ("Capacete Bike LED", "bike helmet with light", 18.2),
        ("Luva Ciclismo Gel", "gel cycling gloves", 6.4),
        ("Ciclocomputador Sem Fio", "wireless bike computer", 13.5),
        ("Bomba Pé Bike", "floor bike pump", 11.8),
        ("Kit Remendo Câmara", "bike tube patch kit", 3.2),
        ("Trava Bike U-Lock", "u lock bike", 14.4),
        ("Suporte Bike Parede", "wall bike rack", 12.2),
        ("Paralama Bike Kit", "bike fenders set", 8.7),
        ("Squeeze Bike 750ml", "bike water bottle 750ml", 4.9),
        ("Suporte Squeeze Guidão", "handlebar bottle cage", 3.6),
        ("Pedal Plataforma Bike", "flat bike pedals", 9.4),
        ("Selim Gel Conforto", "gel bike saddle", 11.6),
        ("Capa Selim Gel", "gel seat cover bike", 5.8),
        ("Farol Traseiro Piscante", "rear bike strobe light", 4.2),
        ("Espelho Retrovisor Bike", "bike rearview mirror", 3.9),
        ("Buzina Elétrica Bike", "electric bike horn", 5.4),
        ("Relógio Esportivo GPS", "gps running watch", 28.0),
        ("Cinta Cardíaca Bluetooth", "bluetooth heart rate strap", 16.8),
        ("Braçadeira Celular Corrida", "running phone armband", 4.7),
        ("Viseira Corrida", "running visor", 3.8),
        ("Cinto Número Peito", "race bib belt", 5.1),
        ("Bastão Caminhada Par", "trekking poles pair", 17.6),
        ("Mochila Hidratação 2L", "2l hydration backpack", 19.4),
        ("Lanterna Cabeça 500lm", "500 lumen headlamp", 9.8),
        ("Apito Emergência Trilha", "emergency whistle hiking", 2.6),
        ("Bússola Militar", "military compass", 5.3),
        ("Saco Dormir 5°C", "sleeping bag 5 degree", 24.8),
        ("Isolante Térmico Yoga Camp", "camping sleeping pad", 13.2),
        ("Barraca 2 Pessoas", "2 person tent", 36.0),
        ("Hamaca Rede Camping", "camping hammock", 14.6),
        ("Fogareiro Portátil", "portable camping stove", 12.8),
        ("Caneca Térmica 500ml", "500ml insulated mug", 8.4),
        ("Garrafa Térmica 1L Inox", "1l stainless thermos", 11.2),
        ("Kit Talher Camping", "camping cutlery set", 4.8),
        ("Toalha Microfibra Viagem", "travel microfiber towel", 6.2),
        ("Squeeze Motivacional 2L", "2l motivational bottle", 7.6),
        ("Coqueteleira 600ml 3pç", "protein shaker 3 piece", 5.4),
    ],
    "Bebê": [
        ("Mamadeira Anticólica 260ml", "anti colic baby bottle 260ml", 6.8),
        ("Bico Mamadeira Kit 4", "baby bottle nipples 4", 3.6),
        ("Escova Limpa Mamadeira", "baby bottle brush", 3.2),
        ("Esterilizador Micro-ondas", "microwave baby sterilizer", 11.4),
        ("Secador Mamadeira Árvore", "bottle drying rack tree", 7.8),
        ("Dispenser Leite Pó", "formula milk dispenser", 4.4),
        ("Pote Papinha Vidro Kit 6", "baby food glass jars 6", 8.2),
        ("Processador Papinha", "baby food maker", 22.6),
        ("Colher Termo-sensível Kit 3", "temperature baby spoons 3", 3.9),
        ("Kit Talher Bebê Silicone", "silicone baby utensils", 5.2),
        ("Copo Transição 360", "360 sippy cup", 6.4),
        ("Canudo Silicone Reposição", "replacement silicone straw baby", 2.8),
        ("Babador Bandana Kit 5", "bandana bibs 5", 6.1),
        ("Babador Manga Longa", "long sleeve baby bib", 5.6),
        ("Avental Amamentação", "nursing cover apron", 8.4),
        ("Conchas Amamentação", "nursing milk catcher", 7.2),
        ("Absorvente Seios Kit 30", "nursing pads 30", 5.8),
        ("Bomba Tira-Leite Elétrica", "electric breast pump", 28.4),
        ("Saco Armazenar Leite 50un", "breast milk storage bags 50", 6.9),
        ("Almofada Amamentação Compacta", "compact nursing pillow", 9.6),
        ("Travesseiro Recém-nascido", "newborn baby pillow", 7.4),
        ("Ninho Redutor Berço", "baby nest lounger", 16.8),
        ("Protetor Berço Lateral", "crib bumper pads", 11.2),
        ("Mosquiteiro Berço", "crib mosquito net", 6.3),
        ("Móbile Musical Berço", "musical crib mobile", 13.6),
        ("Projetor Céu Estrelado", "star projector night light baby", 12.4),
        ("Luz Noturna Sensor", "night light motion baby", 7.1),
        ("White Noise Machine", "white noise machine baby", 15.8),
        ("Monitor Respiração Tapete", "baby breathing monitor pad", 32.0),
        ("Termômetro Infravermelho", "infrared baby thermometer", 11.6),
        ("Aspirador Nasal Elétrico", "electric nasal aspirator", 9.8),
        ("Soro Fisiológico Spray", "baby saline spray", 3.4),
        ("Kit Higiene Bebê 8pç", "baby grooming kit 8", 8.6),
        ("Tesoura Unha Bebê", "baby nail scissors", 3.1),
        ("Escova e Pente Recém-nascido", "newborn brush comb", 3.7),
        ("Toalha Capuz Bebê", "hooded baby towel", 7.6),
        ("Toalhinha Boca Kit 10", "baby washcloths 10", 5.4),
        ("Banheira Dobrável", "foldable baby bathtub", 18.2),
        ("Assento Banheira Bebê", "baby bath seat", 10.4),
        ("Ducha Banho Bebê", "baby bath rinse cup", 3.8),
        ("Termômetro Banheira Flutuante", "floating bath thermometer", 4.2),
        ("Fralda Pano Kit 10", "cloth diapers 10", 12.8),
        ("Capa Fralda Ajustável", "adjustable diaper cover", 6.6),
        ("Trocador Portátil", "portable changing pad", 8.9),
        ("Lixeira Fralda com Tampa", "diaper pail", 14.4),
        ("Saco Impermeável Fralda", "wet dry bag diapers", 5.7),
        ("Creme Assadura Pote", "diaper rash cream", 4.8),
        ("Lenço Umedecido 100un Kit 3", "baby wipes 100x3", 7.9),
        ("Andador Bebê Dobrável", "foldable baby walker", 26.0),
        ("Centro Atividades Bebê", "baby activity center", 34.0),
        ("Gaiola de Atividades", "baby play yard", 29.5),
        ("Cercado Portátil", "portable baby playpen", 31.0),
        ("Cadeirinha Descanso", "baby bouncer chair", 22.4),
        ("Balanço Porta Bebê", "doorway baby jumper", 19.8),
        ("Canguru Ergonômico", "ergonomic baby carrier", 21.6),
        ("Sling Wrap", "baby wrap sling", 14.2),
        ("Protetor Cinto Cadeirinha", "car seat strap covers", 5.2),
        ("Espelho Carro Bebê Grande", "large baby car mirror", 8.4),
        ("Brinquedo Volante Carro", "car steering wheel toy", 9.1),
        ("Chocalho Pulseira Kit 2", "wrist rattles 2", 3.6),
        ("Livro Tecido Sensorial", "soft sensory book", 6.8),
        ("Tapete Espuma 2cm", "2cm foam play mat", 21.4),
        ("Piscina Bolinhas 100un", "ball pit 100 balls", 18.6),
        ("Cavalinho Balanço", "rocking horse toddler", 24.8),
        ("Triciclo Bebê", "toddler tricycle", 28.0),
        ("Patinete Infantil 3 Rodas", "3 wheel kids scooter", 22.2),
        ("Capacete Infantil", "kids helmet", 11.8),
        ("Joelheira Engatinhar Kit 2", "baby crawling knee pads", 4.4),
        ("Protetor Quina Mesa Kit 12", "table corner guards 12", 3.9),
        ("Trava Multiuso Kit 8", "baby safety locks 8", 5.6),
        ("Grade Proteção Fogão", "stove knob covers", 4.7),
        ("Protetor Dedo Porta", "door pinch guard", 3.3),
        ("Rede Cama Elástica Berço", "crib tent", 16.4),
        ("Redinha Banho Recém-nascido", "newborn bath support net", 6.2),
        ("Saco Dormir Bebê", "baby sleeping bag", 13.4),
        ("Manta Cueiro Kit 3", "swaddle blankets 3", 9.2),
        ("Body Manga Longa Kit 5", "long sleeve baby bodysuit 5", 12.6),
        ("Meia Antiderrapante Bebê Kit 6", "baby non slip socks 6", 5.1),
        ("Gorro Recém-nascido Kit 3", "newborn hats 3", 4.6),
        ("Luvinha Recém-nascido Kit 4", "newborn mittens 4", 3.8),
    ],
    "Escritório": [
        ("Suporte Notebook 2 Níveis", "two tier laptop stand", 13.4),
        ("Braço Monitor Duplo", "dual monitor arm", 32.0),
        ("Suporte CPU Torre", "cpu tower stand", 11.6),
        ("Bandeja Teclado Retrátil", "under desk keyboard tray", 18.2),
        ("Mesa Ajustável Laptop Cama", "bed laptop desk", 16.8),
        ("Mesa Dobrável Estudo", "folding study desk", 28.4),
        ("Cadeira Escritório Ergonômica", "ergonomic office chair", 68.0),
        ("Apoio Lombar Malha", "mesh lumbar support", 9.4),
        ("Almofada Assento Gel", "gel seat cushion office", 14.6),
        ("Descansa Pés Oscilante", "rocking foot rest", 12.8),
        ("Tapete Cadeira Escritório", "office chair mat", 19.2),
        ("Gaveteiro 3 Gavetas", "3 drawer mobile pedestal", 26.0),
        ("Arquivo Pasta Suspensa", "hanging file organizer", 11.4),
        ("Caixa Arquivo Morto Kit 5", "archive storage boxes 5", 8.6),
        ("Etiqueta Adesiva Kit 12", "label sticker pack 12", 3.8),
        ("Organizador Papel A4", "a4 paper organizer", 9.2),
        ("Bandeja Documentos 3 Andares", "3 tier document tray", 10.8),
        ("Porta-Canetas Metal", "metal pen holder", 4.6),
        ("Kit Escritório 7pç", "desk accessory set 7", 12.4),
        ("Grampeador Elétrico", "electric stapler", 14.8),
        ("Perfurador 2 Furos", "2 hole punch", 6.2),
        ("Tesoura Titânio", "titanium scissors", 5.4),
        ("Estilete Retrátil", "retractable utility knife", 3.6),
        ("Fita Adesiva Dupla Face", "double sided tape", 2.8),
        ("Cola Bastão Kit 6", "glue sticks 6", 3.4),
        ("Clips Coloridos Caixa", "colored paper clips box", 2.4),
        ("Binder Clip Kit 60", "binder clips 60", 4.1),
        ("Elastico Escritório Caixa", "rubber bands office", 2.6),
        ("Marcador Página Kit 400", "page markers 400", 3.2),
        ("Post-it Transparente", "transparent sticky notes", 3.9),
        ("Caderno Pontilhado A5", "dotted notebook a5", 5.8),
        ("Planner Semanal", "weekly planner notebook", 6.4),
        ("Caneta Gel Preta Kit 12", "black gel pens 12", 5.2),
        ("Marca-Texto Pastel Kit 6", "pastel highlighters 6", 4.8),
        ("Lápis Grafite HB Kit 20", "hb pencils 20", 3.7),
        ("Apontador Elétrico", "electric pencil sharpener", 8.6),
        ("Borracha Branca Kit 10", "white erasers 10", 2.9),
        ("Régua Metal 30cm", "metal ruler 30cm", 2.7),
        ("Compasso Escolar", "school compass", 3.4),
        ("Transferidor e Esquadro", "protractor set square", 3.1),
        ("Calculadora Científica", "scientific calculator", 9.8),
        ("Calculadora Mesa Grande", "large desktop calculator", 8.4),
        ("Quadro Cortiça 40x60", "cork board 40x60", 8.9),
        ("Quadro Avisos Feltro", "felt letter board", 7.6),
        ("Ímã Quadro Branco Kit 20", "whiteboard magnets 20", 3.8),
        ("Apagador Magnético", "magnetic whiteboard eraser", 2.8),
        ("Caneta Quadro Branco Kit 8", "whiteboard markers 8", 4.6),
        ("Flip Chart Tripé", "tripod flip chart", 22.0),
        ("Projetor Mini HDMI", "mini hdmi projector", 38.0),
        ("Tela Projeção 84 Pol", "84 inch projector screen", 29.5),
        ("Apontador Laser Verde", "green laser pointer", 6.8),
        ("Crachá Retrátil Kit 10", "retractable badge holder 10", 6.2),
        ("Cordão Crachá Personalizado", "lanyard badge strap", 2.4),
        ("Porta-Crachá Rígido", "hard badge holder", 2.2),
        ("Carimbo Automático", "self inking stamp", 7.4),
        ("Almofada Carimbo", "stamp pad", 2.6),
        ("Fragmentadora 8 Folhas", "8 sheet paper shredder", 24.8),
        ("Encadernadora Espiral", "spiral binding machine", 31.0),
        ("Plastificadora A4", "a4 laminator", 21.6),
        ("Filme Plastificação 100un", "laminating pouches 100", 8.2),
        ("Guilhotina Papel A4", "a4 paper cutter", 16.4),
        ("Refiladora 4 em 1", "4 in 1 paper trimmer", 18.8),
        ("Suporte Fone RGB", "rgb headphone stand", 9.6),
        ("Hub USB Mesa 8 Portas", "8 port desk usb hub", 12.8),
        ("Carregador Indução Mesa", "desk wireless charger pad", 9.2),
        ("Relógio Mundo Duplo", "dual time world clock", 11.4),
        ("Estação Meteoro Mesa", "desk weather station", 14.6),
        ("Umidificador Mesa 400ml", "400ml desk humidifier", 10.2),
        ("Planta Mesa Artificial", "desk artificial plant", 5.6),
        ("Porta-Retrato Digital 10", "10 inch digital photo frame", 28.4),
        ("Calendário Mesa 2026", "2026 desk calendar", 4.2),
        ("Bloco Rascunho Cubo", "memo cube pad", 3.6),
        ("Clips Dispenser Magnético", "magnetic clip dispenser", 4.8),
        ("Fita Corretiva Kit 6", "correction tape 6", 4.4),
        ("Marca Texto Dual Tip", "dual tip highlighters", 5.1),
        ("Caneta Borracha Elétrica", "electric eraser pen", 6.3),
        ("Pasta Sanfonada 13 Div", "13 pocket expanding file", 7.8),
        ("Envelope Plástico A4 Kit 20", "a4 plastic envelopes 20", 6.6),
        ("Protetor Folha A4 100un", "sheet protectors 100", 5.9),
        ("Grampos 26/6 Caixa", "26/6 staples box", 2.3),
    ],
    "Cozinha": [
        ("Airfryer 4L Digital", "4l digital air fryer", 42.0),
        ("Panela Elétrica Arroz 1L", "1l rice cooker", 18.6),
        ("Chaleira Elétrica 1.7L", "1.7l electric kettle", 16.4),
        ("Cafeteira Cápsula", "capsule coffee machine", 38.0),
        ("Moedor Café Elétrico", "electric coffee grinder", 14.8),
        ("Prensa Francesa 800ml", "french press 800ml", 11.2),
        ("Leiteira Espuma Elétrica", "electric milk frother", 13.6),
        ("Torradeira 2 Fatias", "2 slice toaster", 15.8),
        ("Sanduicheira Grill", "sandwich press grill", 17.4),
        ("Panqueca Elétrica", "electric crepe maker", 16.2),
        ("Waffle Maker", "waffle maker", 18.8),
        ("Panela Pressão Elétrica 5L", "5l electric pressure cooker", 48.0),
        ("Slow Cooker 3.5L", "3.5l slow cooker", 24.6),
        ("Sous Vide Portátil", "portable sous vide", 32.0),
        ("Mixer de Mão 3 em 1", "immersion blender 3 in 1", 19.4),
        ("Batedeira Planetária Mini", "mini stand mixer", 36.0),
        ("Liquidificador Portátil", "portable blender bottle", 14.2),
        ("Espremedor Laranja Elétrico", "electric citrus juicer", 16.8),
        ("Centrífuga Sucos", "centrifugal juicer", 28.4),
        ("Desidratador Alimentos", "food dehydrator", 34.0),
        ("Máquina Macarrão Manual", "manual pasta machine", 18.2),
        ("Cilindro Massa", "dough roller", 12.6),
        ("Forma Pão Antiaderente", "nonstick loaf pan", 6.4),
        ("Assadeira Retangular Kit 3", "baking pan set 3", 11.8),
        ("Forma Cupcake 12", "12 cup muffin tin", 6.8),
        ("Saco Confeitar Kit 16", "piping bag set 16", 5.6),
        ("Espátula Silicone Kit 4", "silicone spatula 4", 4.8),
        ("Rolo Massa Ajustável", "adjustable rolling pin", 7.4),
        ("Anel Formador Hambúrguer", "burger press ring", 4.2),
        ("Grelha Churrasco Portátil", "portable grill pan", 13.4),
        ("Espeto Giratório Elétrico", "electric rotisserie skewer", 21.6),
        ("Termômetro Forno", "oven thermometer", 4.6),
        ("Timer Cozinha Magnético", "magnetic kitchen timer", 3.8),
        ("Balança Colher Digital", "digital spoon scale", 6.2),
        ("Copo Medidor Inox Kit", "stainless measuring cups", 5.4),
        ("Colher Medida Kit 6", "measuring spoons 6", 3.2),
        ("Tábua Bambu 3 Tamanhos", "bamboo cutting board 3", 12.8),
        ("Afiador Faca Elétrico", "electric knife sharpener", 14.6),
        ("Jogo Facas 6pç Suporte", "6 piece knife block", 19.8),
        ("Tesoura Cozinha Multifunção", "kitchen shears multifunctional", 5.8),
        ("Descascador Julienne", "julienne peeler", 3.4),
        ("Cortador Espiral", "spiralizer vegetable", 7.2),
        ("Fatiador Ovo", "egg slicer", 3.1),
        ("Separador Gema", "egg yolk separator", 2.2),
        ("Batedor Fouet Inox", "stainless balloon whisk", 3.6),
        ("Concha e Espumadeira Kit", "ladle skimmer set", 5.2),
        ("Pegador Massa", "pasta tongs", 3.3),
        ("Pincel Culinário Silicone", "silicone pastry brush", 2.8),
        ("Peneira Inox Kit 3", "stainless sieve set 3", 6.6),
        ("Funil Inox Kit 3", "stainless funnel 3", 4.4),
        ("Ralador Caixa 4 Faces", "box grater 4 side", 5.6),
        ("Amassador Batata", "potato masher", 3.9),
        ("Abridor Lata Manual", "manual can opener", 3.4),
        ("Saca-Rolhas 2 Estágios", "waiters corkscrew", 4.1),
        ("Tampa Panela Universal", "universal pot lid", 6.8),
        ("Descanso Panela Silicone Kit 4", "silicone trivet 4", 5.1),
        ("Luva Forno Extra Longa", "extra long oven mitt", 5.7),
        ("Avental Impermeável", "waterproof kitchen apron", 6.4),
        ("Pano Prato Kit 8", "kitchen towels 8", 6.2),
        ("Escorredor Pratos Inox", "stainless dish rack", 13.8),
        ("Porta Detergente Dispenser", "sink soap pump caddy", 6.9),
        ("Escova Limpa Garrafa", "bottle cleaning brush", 3.2),
        ("Esponja Mágica Kit 12", "magic eraser sponges 12", 4.8),
        ("Rodo Pia Silicone", "silicone sink squeegee", 3.6),
        ("Lixeira Pia Embutir", "in sink strainer trash", 5.4),
        ("Filtro Ralo Pia", "sink drain strainer", 2.6),
        ("Organizador Tampa Panela", "pot lid organizer", 8.2),
        ("Suporte Copo Armário", "under cabinet cup holder", 7.4),
        ("Gancho Xícara Kit 8", "mug hooks 8", 4.2),
        ("Porta Temperos Giratório", "rotating spice rack", 11.6),
        ("Pote Mantimento 1.5L Kit 5", "1.5l pantry jars 5", 12.4),
        ("Clip Saco Alimento Kit 20", "bag clips 20", 3.8),
        ("Bomba Vácuo Potes", "vacuum pump food jars", 9.6),
        ("Filme Plástico Dispenser", "cling film dispenser", 5.2),
        ("Papel Manteiga 50m", "parchment paper 50m", 4.6),
        ("Saco Assar Kit 20", "oven roasting bags 20", 4.4),
        ("Forma Gelo Esfera", "sphere ice mold", 5.8),
        ("Copo Whisky Cristal Kit 4", "whisky glasses 4", 12.2),
        ("Coqueteleira Bar 750ml", "750ml cocktail shaker", 8.8),
        ("Saca-Rolhas Elétrico", "electric wine opener", 14.4),
    ],
}


def is_original(item: dict) -> bool:
    tag = item.get("tag") or ""
    prefix = PREFIX.get(tag)
    if not prefix:
        return False
    try:
        num = int(str(item["id"]).split("-")[-1])
    except ValueError:
        return False
    return num in ORIGINAL.get(tag, ())


def main() -> None:
    raw = json.loads(SRC.read_text(encoding="utf-8"))
    base = [item for item in raw if is_original(item)]
    by_cat: dict[str, list[dict]] = {}
    for item in base:
        by_cat.setdefault(item["tag"], []).append(item)
    for cat in ORIGINAL:
        assert len(by_cat.get(cat, [])) == 20, (cat, len(by_cat.get(cat, [])))
        assert len(EXTRA[cat]) == 80, (cat, len(EXTRA[cat]))

    extra: list[dict] = []
    for cat, items in EXTRA.items():
        n = NEXT_ID[cat]
        prefix = PREFIX[cat]
        gallery = [p["image"] for p in by_cat[cat]]
        scored = [
            (item, set(re.findall(r"[a-z0-9]{3,}", (item["name"] + " " + (item.get("search") or "")).lower())))
            for item in by_cat[cat]
        ]
        for i, (name, query, usd_cost) in enumerate(items):
            cost = round(usd_cost * USD, 2)
            want = set(re.findall(r"[a-z0-9]{3,}", f"{name} {query}".lower()))
            pick = max(scored, key=lambda pair: len(want & pair[1]))
            image = pick[0]["image"] if len(want & pick[1]) else gallery[i % len(gallery)]
            extra.append(
                {
                    "id": f"{prefix}-{n:03d}",
                    "name": name,
                    "cost": cost,
                    "price": round(cost / 0.70, 2) if cost * 2 > 150 else round(cost * 2, 2),
                    "image": image,
                    "tag": cat,
                    "blurb": f"{cat} · envio após a confirmação do pagamento.",
                    "stock": 30 + (n % 40),
                    "supplier": "AliExpress",
                    "supplierUrl": f"https://pt.aliexpress.com/w/wholesale-{quote_plus(query)}.html",
                    "search": query,
                }
            )
            n += 1

    products = base + extra
    assert len(products) == 1000, len(products)
    names = [p["name"] for p in products]
    assert len(names) == len(set(names)), "nome repetido"
    assert len({p["id"] for p in products}) == 1000

    SRC.write_text(json.dumps(products, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    rows = [
        {
            "id": item["id"],
            "categoria": item["tag"],
            "produto": item["name"],
            "custo_brl": f"{item['cost']:.2f}".replace(".", ","),
            "venda_brl": f"{item['price']:.2f}".replace(".", ","),
            "aliexpress": item.get("supplierUrl") or "",
            "loja": f"https://alvaloja.store/produto.html?id={item['id']}",
        }
        for item in products
    ]
    csv_path = ROOT / "data" / "fornecedores.csv"
    with csv_path.open("w", encoding="utf-8-sig", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()), delimiter=";")
        writer.writeheader()
        writer.writerows(rows)
    print(f"gerados {len(products)} produtos únicos")


if __name__ == "__main__":
    main()
